defaultProject: gallegos-qbd-poc
defaultDataset: bronze
defaultLocation: US
defaultAssertionDataset: qdb_assertions
dataformCoreVersion: 3.0.42


vars:
  raw_dataset: raw
  bronze_dataset: bronze
  silver_dataset: silver
  gold_dataset: gold
  reporting_dataset: reporting